# Generated by Django 4.2.1 on 2023-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="assignments",
            field=models.ManyToManyField(
                blank=True, related_name="sections", to="courses_app.assignment"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="quizzes",
            field=models.ManyToManyField(
                blank=True, related_name="sections", to="courses_app.quiz"
            ),
        ),
    ]
