# Generated by Django 4.2.1 on 2023-07-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Assignment",
                to="courses_app.section",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Quiz",
                to="courses_app.section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses_app.course",
            ),
        ),
    ]
