# Generated by Django 4.2.1 on 2023-07-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0002_alter_assignment_section_alter_quiz_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Assignment",
                to="courses_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_quizzes",
                to="courses_app.section",
            ),
        ),
    ]
