# Generated by Django 4.2.1 on 2023-07-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0002_alter_section_assignments_alter_section_quizzes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, upload_to="courses/images"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_quizzes",
                to="courses_app.course",
            ),
        ),
    ]
