# Generated by Django 4.2.1 on 2023-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_courses_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/videos'),
        ),
    ]
