# Generated by Django 4.2.1 on 2023-07-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0003_alter_course_course_image_alter_quiz_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(upload_to="courses/images"),
        ),
    ]
