# Generated by Django 4.2.1 on 2023-06-29 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_courses_course_image_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.courses')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses_app.sections'),
        ),
    ]
