import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "photoshop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "html",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "css",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "javascript",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "ES6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "database",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "data",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "small data",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://media.istockphoto.com/id/1219865135/photo/double-exposure-image-of-business-profit-growth.jpg?s=1024x1024&w=is&k=20&c=0gtg3kXX7ns4htm3dQTDwpO9I5Jq9mtZSczFbKeJbQU=",
    title: "big data",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
];

export default data;
