# Generated by Django 4.2.1 on 2023-07-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0003_alter_course_course_image_alter_quiz_course"),
        ("Assign_Quizzes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("quiz_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("deadline_days", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses_app.course",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Assign_Quizzes.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quizsubmission",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Assign_Quizzes.quiz"
            ),
        ),
    ]
