# Generated by Django 4.2.1 on 2023-07-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assign_Quizzes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizoption",
            name="question",
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="options",
            field=models.ManyToManyField(to="Assign_Quizzes.quizoption"),
        ),
    ]
