# Generated by Django 4.2.1 on 2023-07-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Assign_Quizzes", "0003_remove_quizoption_question_quizquestion_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="options",
        ),
        migrations.AddField(
            model_name="quizoption",
            name="question",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Assign_Quizzes.quizquestion",
            ),
            preserve_default=False,
        ),
    ]
